// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConstVisualizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "ConstVisualizer.5bee6ae1-47a5-4255-897f-45f43d47b2be";
        public const string Name = "Const Visualizer";
        public const string Description = @"View the value of constants inline when they're used in code.";
        public const string Language = "en-US";
        public const string Version = "1.23.1";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
